### PR TITLE
Added screen shot

### PR DESCRIPTION
**Pull request by pranaay**
plej agcept

### CODE REVIEW

**Comment by Aniket-Pradhan** [comment]
I was expecting something like [this](https://github.com/dinedal/textql#textql).

Anyways, if you don't have the time for this one, can you get rid of the window bar from the gif?

**Comment by pranaay** [comment]
i can remove it but dont want to cause it gives the gif an authentic look

**Comment by Aniket-Pradhan** [comment]
I agree with that. But, at least change the terminal emulator. This one looks shit. Get a better one, like Hyper or uxterm.

**Comment by pranaay** [comment]
Hahahahhaha 
You are shit

**Comment by Aniket-Pradhan** [comment]
I know... 
Imma add this.

**Pull request merged**
